import { useEffect, useMemo, useState } from 'react'
import { createFileRoute } from '@tanstack/react-router'
import { useAppDispatch, useAppSelector } from '../hooks'
import { addToCart, clearNotice, publishProduct, removeFromCart, setCartOpen, setCategory, setQuery, setSellerOpen, showNotice, type Category, type Product } from '../features/marketplaceSlice'

export const Route = createFileRoute('/')({ component: Marketplace })
const categories: Category[] = ['All', 'Vegetables', 'Fruits', 'Dairy', 'Pantry']
const fallback = 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=700&q=80'
const money = (value: number) => `₹${value.toLocaleString('en-IN')}`

function Marketplace() {
  const dispatch = useAppDispatch()
  const { products, cart, category, query, isCartOpen, isSellerOpen, notice } = useAppSelector(state => state.marketplace)
  const [form, setForm] = useState({ name: '', price: '', unit: '', category: 'Vegetables' as Product['category'], farm: '', image: '' })
  const visible = useMemo(() => products.filter(product => (category === 'All' || product.category === category) && `${product.name} ${product.farm}`.toLowerCase().includes(query.toLowerCase())), [products, category, query])
  const cartItems = cart.map(line => ({ ...line, product: products.find(product => product.id === line.id) })).filter((line): line is typeof line & { product: Product } => Boolean(line.product))
  const count = cart.reduce((total, line) => total + line.quantity, 0)
  const total = cartItems.reduce((sum, line) => sum + line.quantity * line.product.price, 0)
  useEffect(() => { if (!notice) return; const timer = window.setTimeout(() => dispatch(clearNotice()), 2200); return () => window.clearTimeout(timer) }, [notice, dispatch])
  const publish = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const product: Product = { id: crypto.randomUUID(), name: form.name.trim(), price: Number(form.price), unit: form.unit.trim(), category: form.category, farm: form.farm.trim(), image: form.image.trim() || fallback, tag: 'New harvest' }; dispatch(publishProduct(product)); setForm({ name: '', price: '', unit: '', category: 'Vegetables', farm: '', image: '' }) }
  return <>
    <div className="announcement">🌿 &nbsp;Free delivery on orders over ₹499 <span>•</span> Supporting local growers, one basket at a time.</div>
    <header className="site-header"><a className="brand" href="#home"><span className="brand-mark">f</span>farmly</a><nav className="main-nav"><a className="active" href="#market">Shop</a><a href="#how-it-works">How it works</a><a href="#stories">Farmer stories</a></nav><div className="header-actions"><button className="text-button" onClick={() => dispatch(setSellerOpen(true))}>Sell with us</button><button className="cart-button" onClick={() => dispatch(setCartOpen(true))}><span className="cart-icon">⌑</span><span>Basket</span><b>{count}</b></button></div></header>
    <main id="home"><section className="hero"><div className="hero-copy"><p className="eyebrow"><i /> GROWN CLOSE TO HOME</p><h1>Good food,<br /><em>grown honestly.</em></h1><p>Buy seasonal produce directly from the people who grow it. Freshly harvested, fairly priced, and full of flavour.</p><div className="hero-actions"><a className="button primary" href="#market">Shop the market <span>→</span></a><button className="button subtle" onClick={() => dispatch(setSellerOpen(true))}>Start selling</button></div><div className="hero-proof"><div className="avatar-stack"><img src="https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=80&q=80" alt="" /><img src="https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=80&q=80" alt="" /><img src="https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=80&q=80" alt="" /></div><span><strong>2,000+ happy tables</strong><br />fed by local farms</span></div></div><div className="hero-art"><div className="sun-disc" /><div className="arch-photo"><img src="https://images.unsplash.com/photo-1500595046743-cd271d694d30?auto=format&fit=crop&w=1200&q=85" alt="Farmer harvesting vegetables" /></div><div className="floating-tag tag-top">✦ Picked this morning</div><div className="floating-tag tag-bottom"><span>🥕</span><b>100%<small>local produce</small></b></div></div></section>
      <section className="benefits" id="how-it-works"><Benefit icon="◎" title="Picked at peak freshness" copy="From farm to your doorstep" /><Benefit icon="♧" title="Fair for farmers" copy="They set the price, always" /><Benefit icon="⌂" title="Grown nearby" copy="Know exactly where it came from" /></section>
      <section className="market" id="market"><div className="section-heading"><div><p className="eyebrow">THE MARKET</p><h2>Fresh finds, right now.</h2></div><button className="view-all" onClick={() => { dispatch(setCategory('All')); dispatch(setQuery('')) }}>View all produce <span>→</span></button></div><div className="market-tools"><div className="search"><span>⌕</span><input value={query} onChange={event => dispatch(setQuery(event.target.value))} type="search" placeholder="Search for produce or a farmer" /></div><div className="filters">{categories.map(item => <button key={item} onClick={() => dispatch(setCategory(item))} className={`filter ${category === item ? 'active' : ''}`}>{item === 'Dairy' ? 'Dairy & eggs' : item}</button>)}</div></div><div className="product-grid">{visible.map(product => <article className="product-card" key={product.id}><div className="product-image"><img src={product.image} alt={product.name} onError={event => { event.currentTarget.src = fallback }} /><span className="product-label">{product.tag}</span><button className="add-product" onClick={() => dispatch(addToCart(product.id))} aria-label={`Add ${product.name} to basket`}>+</button></div><div className="product-info"><h3>{product.name}</h3><p>{product.farm}</p><strong>{money(product.price)} <small>{product.unit}</small></strong></div></article>)}</div>{visible.length === 0 && <p className="empty-products">Nothing found here yet. Try another search.</p>}</section>
      <section className="seller-banner" id="stories"><div><p className="eyebrow">ARE YOU A GROWER?</p><h2>Your harvest deserves<br />a <em>good home.</em></h2><p>List your produce, set your price, and reach people in your community who care about good food.</p><button className="button cream" onClick={() => dispatch(setSellerOpen(true))}>Become a seller <span>→</span></button></div><div className="seller-image"><img src="https://images.unsplash.com/photo-1464226184884-fa280b87c399?auto=format&fit=crop&w=900&q=85" alt="Farmer working in a field" /><div className="quote">“Farmly lets me focus on what I love — growing good food.”<small>— Anjali, 3rd generation farmer</small></div></div></section>
    </main><footer><a className="brand" href="#home"><span className="brand-mark">f</span>farmly</a><p>Better food begins at the farm.</p><span>© 2026 Farmly</span></footer>
    {isCartOpen && <><div className="overlay show" onClick={() => dispatch(setCartOpen(false))} /><aside className="drawer open"><div className="drawer-head"><div><p className="eyebrow">YOUR ORDER</p><h2>Your basket</h2></div><button className="icon-close" onClick={() => dispatch(setCartOpen(false))}>×</button></div>{cartItems.length ? <div className="cart-items">{cartItems.map(line => <div className="cart-item" key={line.id}><img src={line.product.image} alt="" /><div><h3>{line.product.name}</h3><p>{line.quantity} × {money(line.product.price)} · {line.product.unit}</p><strong>{money(line.quantity * line.product.price)}</strong></div><button onClick={() => dispatch(removeFromCart(line.id))}>×</button></div>)}</div> : <div className="cart-empty"><span>⌑</span><p>Your basket is waiting.</p><small>Add something fresh from the market.</small></div>}<div className="cart-footer"><div><span>Subtotal</span><strong>{money(total)}</strong></div><button className="button primary checkout" onClick={() => dispatch(showNotice(cartItems.length ? 'Checkout is ready for the next step!' : 'Your basket is still empty'))}>Continue to checkout <span>→</span></button></div></aside></>}
    {isSellerOpen && <dialog className="seller-modal" open><button className="icon-close modal-close" onClick={() => dispatch(setSellerOpen(false))}>×</button><div className="modal-intro"><p className="eyebrow">SELL ON FARMLY</p><h2>Share your harvest<br />with your community.</h2><p>Fill in your first product listing. It will appear in the market right away.</p><div className="mini-stat"><b>Zero listing fee</b><span>You keep 92% of every sale</span></div></div><form onSubmit={publish}><label>Product name<input required value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} placeholder="e.g. Heirloom tomatoes" /></label><div className="form-row"><label>Price (₹)<input required min="1" type="number" value={form.price} onChange={event => setForm({ ...form, price: event.target.value })} placeholder="120" /></label><label>Unit<input required value={form.unit} onChange={event => setForm({ ...form, unit: event.target.value })} placeholder="per kg" /></label></div><label>Category<select value={form.category} onChange={event => setForm({ ...form, category: event.target.value as Product['category'] })}>{categories.slice(1).map(item => <option key={item}>{item}</option>)}</select></label><label>Your farm name<input required value={form.farm} onChange={event => setForm({ ...form, farm: event.target.value })} placeholder="e.g. Green Acre Farm" /></label><label>Photo URL <small>(optional)</small><input type="url" value={form.image} onChange={event => setForm({ ...form, image: event.target.value })} placeholder="https://images..." /></label><button className="button primary submit-product">Publish product <span>→</span></button></form></dialog>}
    {notice && <div className="toast show" role="status">{notice}</div>}
  </>
}
function Benefit({ icon, title, copy }: { icon: string; title: string; copy: string }) { return <div><span>{icon}</span><p><b>{title}</b><small>{copy}</small></p></div> }
